### ISSUE TITLE
ol-popup should contain properties about its current location

### ISSUE THREAD

**Issue by roemhildtg** [roemhildtg/geocola#4]
There should be a x and y property in the ol-popup component to allow users to create templates that use these properties.

**Comment by roemhildtg** [comment]
For the x and y property a get function should be defined which calls [`overlay.getPosition`](http://openlayers.org/en/v3.5.0/apidoc/ol.Overlay.html#getPosition)

**Comment by green3g** [comment]
Scope is leaked in popup now.
